title: Leading the Future of AI and Public Archives
description: Resources for a virtual workshop series organized by National Archives Office of Innovation, Virginia Tech’s University Libraries and Center for Humanities, Library of Congress Labs, and Smithsonian OCIO Data Science Lab.
theme: jekyll-theme-cayman
github:
  is_project_page: false
