title: Leading the Future of AI and Public Archives
description: Resources for a virtual workshop organized by National Archives Office of Innovation, Virginia Tech’s University Libraries and Center for Humanities, Library of Congress Labs, and Smithsonian OCIO Data Science Lab, held May 6th and May 13th, 2022.
theme: jekyll-theme-cayman
